Added drupal-tag

diff --git a/drupal-release b/drupal-release
--- a/drupal-release
+++ b/drupal-release
@@ -1,5 +1,8 @@
 #!/bin/bash
 
+# TODO Check permission before starting
+# TODO Dump both dbs as single line inserts and diff them
+
 set -e
 
 source `dirname $0`/colours
@@ -16,42 +19,7 @@ fi
 DRUPAL_REMOTE_ROOT=/var/www/latest
 DRUPAL_LOCAL_ROOT=`pwd`
 
-#################################
-# Functions
-
-function getRemotePath {
-    export RPATH=`ssh $RUSER@$RHOST realpath /var/www/testing`
-    export CURRENT=`basename $RPATH`
-}
-
-function getVersionElements {
-    export BRAND=`echo $1|awk '{split($0,a,"_"); print a[1]}'`
-    export NOBC=`echo $1|awk '{split($0,a,"_"); print a[2]}'`
-    if [ "$BRAND" == "$1" ]; then
-        NOBC=$BRAND
-        unset BRAND
-    fi
-    export MAJOR_VERSION=`echo $NOBC|awk '{split($0,a,"."); print a[1]}'`
-    export MINOR_VERSION=`echo $NOBC|awk '{split($0,a,"."); print a[2]}'`
-    export PATCH_VERSION=`echo $NOBC|awk '{split($0,a,"."); print a[3]}'`
-}
-
-function aliasname {
-    aliasname=$(echo $1 | awk -F '.' '{print $1}')
-    isnumeric=$(echo $aliasname | grep "[^0-9]")
-    if [ -z "$isnumeric" ]; then
-      # The first element is a numer, it's probably an IP
-      echo $1
-    else
-      echo $aliasname
-    fi
-}
-
-function debug {
-    if [ ! -z "$VERBOSE" ]; then
-        echo -e $1
-    fi
-}
+source `dirname $0`/drupal-functions
 
 function usage {
     echo $USAGE
@@ -113,6 +81,22 @@ done
 shift $((OPTIND-1))
 RUSER=$1
 RHOST=$2
+
+# check the most common write permission
+if [ ! -w "$DRUPAL_LOCAL_ROOT" ] ; then
+    echo -e $COL_RED"Cannot write to ${DRUPAL_LOCAL_ROOT}. Writting change log will fail."$COL_RESET
+    exit 1
+fi
+
+if [ ! -w "$DRUPAL_LOCAL_ROOT/sites/all/drush" ] ; then
+    echo -e $COL_RED"Cannot write to ${DRUPAL_LOCAL_ROOT}/sites/all/drush. Writting alias file log will fail."$COL_RESET
+    exit 1
+fi
+
+if [ ! -w "$DRUPAL_LOCAL_ROOT/sites/default" ] ; then
+    echo -e $COL_RED"Cannot write to ${DRUPAL_LOCAL_ROOT}/sites/default Writting new settings file log will fail."$COL_RESET
+    exit 1
+fi
 
 # Check we have required params
 if [ -z $RUSER ]; then
@@ -259,6 +243,11 @@ ssh ${RUSER}@${RHOST} chmod a-w /var/www/$RELEASE/sites/default/settings.php /va
 
 echo -e $COL_GREEN"Dumping remote DB"$COL_RESET
 ssh ${RUSER}@${RHOST} drush -r /var/www/$CURRENT sql-dump --result-file=/tmp/dump.sql
+
+echo -e $COL_GREEN"Diffing DBs to $DRUPAL_LOCAL_ROOT/${CURRENT}-${RELEASE}.diff"$COL_RESET
+ssh ${RUSER}@${RHOST} drush -r /var/www/$CURRENT sql-dump --ordered-dump > /tmp/${CURRENT}.sql
+drush -r $DRUPAL_LOCAL_ROOT sql-dump --ordered-dump > /tmp/${RELEASE}.sql
+diff /tmp/${CURRENT}.sql /tmp/${RELEASE}.sql > $DRUPAL_LOCAL_ROOT/${CURRENT}-${RELEASE}.diff
 
 echo -e $COL_GREEN"Creating remote DB"$COL_RESET
 ssh ${RUSER}@${RHOST} "bash mysql-create-user-and-db -u $RELEASE -p $RELEASE -m $MYSQL_ROOT_PASSWORD"
diff --git a/drupal-tag b/drupal-tag
--- a/drupal-tag
+++ b/drupal-tag
@@ -1,25 +1,101 @@
 #!/bin/bash
 
-NO_ARGS=0
-USAGE="$0 CURTAG NEWTAG"
-if [ $# -eq "$NO_ARGS" ]; then
+USAGE="$0 [-o CURTAG] [-n NEWTAG] [-h] [/path/to/repo]"
+
+function usage {
     echo $USAGE
+    cat <<EOF
+
+Tag a new release on a repo.
+
+-o Current tag
+  Override the previous tag to build the change log from
+-n New tag
+  Overrdie the new tag value, will skip the bump section
+-b <major|minor|bump>]
+  Sites are release in a x.y.z format where versions are major.minor.patch
+  The script will bump that version by one in the category specified. If
+  ommitted the script will ask.
+EOF
+}
+
+while getopts "o:n:b:h" options; do
+    case $options in
+        o) OLDBRANCH="$OPTARG";;
+        n) NEWBRANCH="$OPTARG";;
+        b) BUMP="$OPTARG";;
+        h) usage; exit;;
+    esac
+done 
+
+source `dirname $0`/drupal-functions
+
+shift $((OPTIND-1))
+if [ ! -z "$@" ]; then
+    ROOTPATH=$@
+else
+    ROOTPATH=`pwd`
+fi
+
+# find .git folder
+for x in `find $ROOTPATH -type d -name .git`; do
+    GIT=`dirname $x`
+    count=$(($count + 1))
+done
+
+if [ -z "$count" ]; then
+    echo $USAGE
+    echo "Unable to find .git folder, aborting"
+    exit 1
+elif [ "$count" -gt "1" ]; then
+    echo $USAGE
+    echo "Found multiple git repos, cannot continue."
     exit 1
 fi
 
-CUR_TAG=$1
-NEW_TAG=$2
+echo "Git found at $x, git folder set to $GIT"
+GITCMD="git -C $GIT"
 
-if [ -z "$CUR_TAG" ] || [ -z "$NEW_TAG" ]; then
-    echo $USAGE
-    exit 1
+# find latest tag
+if [ -z "$OLDBRANCH" ]; then
+    CUR_TAG=`$GITCMD describe --abbrev=0 --tags`
+else
+    CUR_TAG=$OLDBRANCH
 fi
 
-echo $NEW_TAG > newchangelog.txt
-echo "======" >> newchangelog.txt
-git log --no-merges --format="%ai %aN %b %n%n%x09* %s%d%n" $CUR_TAG..master >> newchangelog.txt
-cat changelog.txt >> newchangelog.txt
-mv newchangelog.txt changelog.txt
-git commit -a -m 'Updated change log'
-git tag $NEW_TAG
-git push origin master --tags
+echo CUR_TAG $CUR_TAG
+
+if [ -z "$NEWBRANCH" ]; then
+    getVersionElements $CUR_TAG
+    bumpUp ${MAJOR_VERSION} ${MINOR_VERSION} ${PATCH_VERSION} ${BUMP}
+    NEW_TAG="${MAJOR_VERSION}.${MINOR_VERSION}.${PATCH_VERSION}"
+else
+    NEW_TAG=$NEWBRANCH
+fi
+
+echo NEW_TAG $NEW_TAG
+
+NEWCHANGELOG=$ROOTPATH/newchangelog.txt
+OLDCHANGELOG=$ROOTPATH/changelog.txt
+
+echo $NEW_TAG > $NEWCHANGELOG
+echo "======" >> $NEWCHANGELOG
+$GITCMD log --no-merges --format="%ai %aN %b %n%n%x09* %s%d%n" $CUR_TAG..master >> $NEWCHANGELOG
+
+# Preview the changes
+less $NEWCHANGELOG
+echo "Proceed (Y/n)"
+a=0
+until [ "$a" == "y" ] || [ "$a" == "n" ]; do
+    read b
+    a=`echo $b | tr '[:upper:]' '[:lower:]'`
+done
+if [ "$a" == "n" ]; then
+    exit
+fi
+
+cat changelog.txt >> $NEWCHANGELOG
+mv $NEWCHANGELOG changelog.txt
+$GITCMD commit -a -m 'Updated change log'
+$GITCMD tag $NEW_TAG
+$GITCMD push origin master --tags
